"""Per-cell field map: engine facts, every line a pointer.

`.evo/views/FIELD_MAP.md` is rendered with the other views. One section per
evaluation cell, in contract order: the noise floor in force and its source,
our best value and its holder, the published cap (accepted S# rows bound to
the cell), the gap, every concluded node that claimed the cell with its delta,
verdict and mechanism status, the ablations whose scope covered it and the
observations its claimants banked. Tombstones are round/lane bound and close
the file. The agent's own judgment (`.evo/profile/FIELD_NOTES.md`) is appended
verbatim when it exists; the engine never writes it.
"""
from __future__ import annotations

import json
from typing import Any

import econfig
import egraph
import eutil
import evalid

VIEW_REL = ".evo/views/FIELD_MAP.md"
NOTES_REL = ".evo/profile/FIELD_NOTES.md"
SOTA_REL = ".evo/evidence/SOTA.jsonl"
TOMBSTONES_REL = ".evo/evidence/TOMBSTONES.jsonl"
HEADER = "generated by the engine; do not edit - facts only, every line is a pointer"
LIST_CAP = 12
NOTES_HEADING = "## Notes (agent-written judgment, not engine facts)"
TERRITORY_HEADING = "## Published territory (all cells)"


def render(store: Any, g: dict, cfg: dict, st: dict | None) -> str:
    """Write the view and return its text."""
    text = "\n".join(lines(store, g, cfg, st)) + "\n"
    eutil.write_text(store.views_dir() / "FIELD_MAP.md", text)
    return text


def lines(store: Any, g: dict, cfg: dict, st: dict | None) -> list[str]:
    st = st if isinstance(st, dict) else {}
    idx = egraph.by_id(g)
    frontier_ids = {n["id"] for n in egraph.frontier(g, cfg, st)}
    records = {row["cell"]: row for row in egraph.cell_records(g, cfg)}
    sota_by_cell = _sota_by_cell(store, st)
    metas = {nid: _idea_meta(store, n) for nid, n in idx.items()}
    claims = _claims(idx, metas)
    scopes = _ablation_scopes(idx, metas)
    probe_parents = {nid: str((n.get("parents") or [""])[0] or "") for nid, n in idx.items()
                     if str(n.get("experiment_purpose") or "") == "diagnostic_probe" and n.get("parents")}
    observations = store.observations(st, active_only=True)
    out = [f"# Field map ({HEADER})", "",
           "Ids: N# node (.evo/nodes/N###/), L# lane, R# round, S# SOTA row (.evo/evidence/SOTA.jsonl),",
           "OB# observation (.evo/evidence/OBSERVATIONS.jsonl), TB# tombstone (.evo/evidence/TOMBSTONES.jsonl).",
           "Delta = the node's own settlement against its reference node, read with the floor frozen",
           "for that node. Best = best observed value over every eligible node, retired holders included.",
           ""]
    for cell in econfig.evaluation_cells(cfg):
        out += _cell_section(cell, cfg, st, idx, frontier_ids, records, sota_by_cell,
                             claims, scopes, observations, probe_parents)
        out.append("")
    out += _unattributed_section(idx)
    out += _territory_section(store)
    notes = eutil.rpath(store.repo, NOTES_REL)
    if notes.is_file():
        out += ["", NOTES_HEADING, "", eutil.read_text(notes).rstrip("\n")]
    return out


# ------------------------------------------------------------------ cells ----
def _cell_section(cell: dict, cfg: dict, st: dict, idx: dict[str, dict], frontier_ids: set[str],
                  records: dict[str, dict], sota_by_cell: dict[str, list[dict]],
                  claims: dict[str, set[str]], scopes: dict[str, set[str]],
                  observations: list[dict],
                  probe_parents: dict[str, str] | None = None) -> list[str]:
    cid = str(cell.get("id") or "")
    role = str(cell.get("role") or "")
    result_key = str(cell.get("result_key") or "")
    direction = econfig.result_direction(cfg, result_key)
    title = f"## {cid} - {cell.get('dataset')} / {cell.get('task')} / {cell.get('metric')} - role {role}"
    if role == "diagnostic":
        title += " - never decides"
    out = [title, ""]
    out.append(f"- result_key {result_key} ({direction}); required {str(bool(cell.get('required'))).lower()}; "
               f"min_improvement {_num(cell.get('min_improvement'))}; "
               f"noninferiority_margin {_num(cell.get('noninferiority_margin'))}")
    out.append("- " + _floor_line(cfg, st, cid))
    best = records.get(cid) or _best_row(idx, cfg, cell)
    out.append("- " + _best_line(best, idx))
    best_value = float(best["value"]) if best is not None else None
    caps = sota_by_cell.get(cid, [])
    if caps:
        shown, older = _newest(caps)
        for row in shown:
            out.append("- cap " + _sota_line(row))
        if older:
            out.append(f"- +{older} older SOTA rows on this cell, see the ledger")
        out.append("- " + _gap_line(caps, best_value, direction))
    else:
        out.append("- cap: no accepted SOTA row bound to this cell")
    out += _claimants_block(cid, idx, frontier_ids, claims)
    out += _ablations_block(cid, idx, scopes)
    out += _observations_block(cid, claims, scopes, observations, probe_parents)
    return out


def _floor_line(cfg: dict, st: dict, cid: str) -> str:
    width = econfig.noise_floor(cfg, cid, st)
    source = econfig.noise_floor_source(cfg, cid, st)
    if source == "none":
        return "floor: none recorded (deltas are read at face value)"
    provenance = str((econfig.evaluation_contract(cfg).get("noise_floor_sources") or {}).get(cid) or "")
    where = "engine-measured seed spread (st.observed_noise)" if source == "observed" \
        else "evaluation_contract.noise_floors"
    tail = f", recorded as {provenance}" if provenance and source == "config" else ""
    multiple = econfig.noise_floor_multiple(cfg)
    bar = f"; a real win clears {multiple:g} x = {width * multiple:g}" if multiple != 1.0 else ""
    return f"floor: {width:g} ({source}: {where}{tail}{bar})"


def _best_row(idx: dict[str, dict], cfg: dict, cell: dict) -> dict | None:
    """Same ranking as egraph.cell_records, for the cells that table leaves out."""
    result_key = str(cell.get("result_key") or "")
    direction = econfig.result_direction(cfg, result_key)
    best: dict | None = None
    for n in idx.values():
        if not egraph.observation_eligible(n, cfg):
            continue
        point = econfig.result_value(egraph.cell_raw(n, result_key))
        if point is None:
            continue
        if best is None or (point > best["value"] if direction == "max" else point < best["value"]):
            best = {"cell": str(cell.get("id")), "result_key": result_key, "role": cell.get("role"),
                    "node": str(n.get("id")), "value": float(point), "direction": direction}
    return best


def _best_line(best: dict | None, idx: dict[str, dict]) -> str:
    if best is None:
        return "best: no measurement yet"
    holder = idx.get(str(best.get("node"))) or {}
    bits = [f"best: {float(best['value']):g} held by {best['node']}"]
    if holder.get("round"):
        bits.append(str(holder["round"]))
    if holder.get("lane"):
        bits.append(str(holder["lane"]))
    when = str(holder.get("concluded_at") or "")[:10]
    if when:
        bits.append(f"concluded {when}")
    line = " ".join(bits[:1]) + (f" ({', '.join(bits[1:])})" if len(bits) > 1 else "")
    retired = str(holder.get("retire_reason") or "")
    if retired in ("archived", "pruned"):
        line += f" - {retired}, revive first (evo revive --node {best['node']} --note ...)"
    return line


# ------------------------------------------------------------------- sota ----
def _sota_by_cell(store: Any, st: dict) -> dict[str, list[dict]]:
    raw = [r for r in eutil.read_jsonl(eutil.rpath(store.repo, SOTA_REL), lenient=True)
           if isinstance(r, dict)]
    out: dict[str, list[dict]] = {}
    for row in evalid.accepted_ledger_rows(st, "sota", raw):
        cell = str(row.get("cell") or "")
        if cell:
            out.setdefault(cell, []).append(row)
    return out


def _sota_value(row: dict) -> float | None:
    headline = row.get("headline") if isinstance(row.get("headline"), dict) else {}
    value = headline.get("value")
    return float(value) if isinstance(value, (int, float)) and not isinstance(value, bool) else None


def _sota_line(row: dict) -> str:
    value = _sota_value(row)
    headline = row.get("headline") if isinstance(row.get("headline"), dict) else {}
    return (f"{row.get('id')}: {'-' if value is None else f'{value:g}'} {headline.get('metric') or ''}".rstrip()
            + f", comparability {row.get('comparability') or '-'}, method {_clip(row.get('method'), 60)}"
            + (f" ({row.get('year')})" if row.get("year") else ""))


def _gap_line(caps: list[dict], best_value: float | None, direction: str) -> str:
    exact = [(r, _sota_value(r)) for r in caps if str(r.get("comparability") or "") == "exact"]
    exact = [(r, v) for r, v in exact if v is not None]
    if not exact:
        return "gap: no exact-comparability cap (protocol_adjusted/near_task rows are not subtracted)"
    if best_value is None:
        return "gap: no measurement yet to compare against " + ", ".join(str(r.get("id")) for r, _ in exact)
    parts = []
    for row, value in exact:
        diff = (value - best_value) if direction == "max" else (best_value - value)
        parts.append(f"{row.get('id')} {diff:+g} ({'behind' if diff > 0 else 'ahead' if diff < 0 else 'level'})")
    return "gap to exact caps (cap - best, sign in the cell's direction): " + "; ".join(parts)


# -------------------------------------------------------------- claimants ----
def _idea_meta(store: Any, node: dict) -> dict:
    """Lenient read: a view never blocks on an agent-written file."""
    doc = str(node.get("idea_doc") or "")
    if not doc:
        return {}
    path = eutil.rpath(store.repo, doc.replace(".md", ".meta.json"))
    if not path.is_file():
        return {}
    try:
        meta = json.loads(eutil.read_text(path))
    except json.JSONDecodeError:
        return {}
    return meta if isinstance(meta, dict) else {}


def _claims(idx: dict[str, dict], metas: dict[str, dict]) -> dict[str, set[str]]:
    """node id -> cells it claimed (evaluation_summary.target_cells or claim_scope)."""
    out: dict[str, set[str]] = {}
    for nid, n in idx.items():
        if n.get("status") != "concluded" or n.get("role") in ("baseline", "platform"):
            continue
        if str(n.get("experiment_purpose") or "candidate") in econfig.INSTRUMENTAL_PURPOSES:
            continue
        summary = n.get("evaluation_summary") if isinstance(n.get("evaluation_summary"), dict) else {}
        scope = metas.get(nid, {}).get("claim_scope")
        cells = set(str(c) for c in (summary.get("target_cells") or []))
        if isinstance(scope, dict):
            cells |= set(str(c) for c in (scope.get("target_cells") or []))
        if cells:
            out[nid] = cells
    return out


def _ablation_scopes(idx: dict[str, dict], metas: dict[str, dict]) -> dict[str, set[str]]:
    """ablation node id -> cells its evaluation_scope covered."""
    out: dict[str, set[str]] = {}
    for nid, n in idx.items():
        if n.get("status") != "concluded" or n.get("experiment_purpose") != "targeted_ablation":
            continue
        summary = n.get("evaluation_summary") if isinstance(n.get("evaluation_summary"), dict) else {}
        scope = metas.get(nid, {}).get("evaluation_scope")
        cells = set(str(c) for c in (summary.get("target_cells") or []))
        if isinstance(scope, dict):
            cells |= set(str(c) for c in (scope.get("target_cells") or []))
        if cells:
            out[nid] = cells
    return out


def _claimants_block(cid: str, idx: dict[str, dict], frontier_ids: set[str],
                     claims: dict[str, set[str]]) -> list[str]:
    ids = sorted(nid for nid, cells in claims.items() if cid in cells)
    if not ids:
        return ["- claimed by: no concluded node yet"]
    shown, older = _newest(ids)
    out = ["- claimed by:"]
    for nid in shown:
        out.append("  - " + _claimant_line(cid, idx[nid], nid in frontier_ids))
    if older:
        out.append(f"  - +{older} older claimants, see GRAPH.md")
    return out


def _claimant_line(cid: str, n: dict, on_frontier: bool) -> str:
    summary = n.get("evaluation_summary") if isinstance(n.get("evaluation_summary"), dict) else {}
    row = (summary.get("cells") or {}).get(cid) if isinstance(summary.get("cells"), dict) else None
    row = row if isinstance(row, dict) else {}
    delta = row.get("delta")
    delta_txt = (f"{float(delta):+g} vs {row.get('reference_node') or '-'}"
                 if isinstance(delta, (int, float)) and not isinstance(delta, bool) else "delta -")
    where = ", ".join(str(x) for x in (n.get("lane"), n.get("round")) if x)
    purpose = str(n.get("experiment_purpose") or "candidate")
    tag = "" if purpose == "candidate" else f" [{purpose}]"
    retired = str(n.get("retire_reason") or "")
    tail = f"; {retired} - revive first" if retired in ("archived", "pruned") else ""
    if purpose in econfig.EXPLORATORY_PURPOSES:
        # a scout bets nothing: its numbers are observations, not a claim
        return (f"{n.get('id')}{tag}" + (f" ({where})" if where else "") + f": {delta_txt}, "
                f"cell {row.get('status') or '-'}; observations only (no claim, never a parent){tail}")
    over = summary.get("resource_overrun") if isinstance(summary.get("resource_overrun"), dict) else {}
    over_txt = ("; resources over cap: " + ",".join(
        f"{axis} +{r.get('over_pct'):g}%" if isinstance(r, dict) and isinstance(r.get("over_pct"), (int, float))
        else str(axis) for axis, r in sorted(over.items()))) if over else ""
    deviations = [d for d in (n.get("launch_deviations") or []) if isinstance(d, dict)]
    if deviations:
        over_txt += "; launch changed from plan: " + " / ".join(str(d.get("note") or "")[:80] for d in deviations[-2:])
    return (f"{n.get('id')}{tag}" + (f" ({where})" if where else "") + f": {delta_txt}, "
            f"cell {row.get('status') or '-'}; verdict {n.get('verdict') or '-'}; "
            f"effect {n.get('effect_contract_status') or '-'}{over_txt}; science {egraph.promotion_label(n)}; "
            f"mechanism {egraph.mechanism_label(n)}; "
            f"inheritance frontier {'yes' if on_frontier else 'no'}{tail}")


def _ablations_block(cid: str, idx: dict[str, dict], scopes: dict[str, set[str]]) -> list[str]:
    ids = sorted(nid for nid, cells in scopes.items() if cid in cells)
    if not ids:
        return []
    shown, older = _newest(ids)
    out = ["- ablations whose scope covered this cell:"]
    for nid in shown:
        n = idx[nid]
        result = n.get("ablation_result") if isinstance(n.get("ablation_result"), dict) else {}
        parent = str((n.get("parents") or ["-"])[0] or "-")
        out.append(f"  - {nid} (of {parent}): effect {result.get('effect') or '-'}, "
                   f"supports {result.get('supports') or '-'}, decision {_clip(result.get('decision'), 80)}")
    if older:
        out.append(f"  - +{older} older ablations, see GRAPH.md")
    return out


def _observations_block(cid: str, claims: dict[str, set[str]], scopes: dict[str, set[str]],
                        observations: list[dict], probe_parents: dict[str, str] | None = None) -> list[str]:
    bound = {nid for nid, cells in claims.items() if cid in cells}
    bound |= {nid for nid, cells in scopes.items() if cid in cells}
    # a diagnostic probe claims nothing itself; what it observed belongs
    # under the cells its parent claimed
    bound |= {pid for pid, parent in (probe_parents or {}).items() if parent in bound}
    rows = [r for r in observations if isinstance(r, dict) and str(r.get("node") or "") in bound]
    if not rows:
        return []
    shown, older = _newest(rows)
    out = ["- observations banked by those nodes:"]
    for r in shown:
        out.append(f"  - {r.get('id')} ({r.get('node')}): {_clip(r.get('statement'), 120)}")
    if older:
        out.append(f"  - +{older} older observations, see the ledger")
    return out


# -------------------------------------------------------------- territory ----
def _unattributed_section(idx: dict[str, dict]) -> list[str]:
    """Gains whose kernel an ablation refuted: the numbers are real, the story
    is not. Each line says what the gain then means (paradigm / shell /
    unattributed), which control version to build on, and what to ask next."""
    rows = [n for n in idx.values() if isinstance(n.get("refuted_kernel"), dict)]
    if not rows:
        return []
    out = ["## Gains whose kernel was refuted", "",
           "The ablation found the claimed kernel does not carry the gain. Build on the control",
           "version, never cite the kernel as a cause, and follow the reading:", ""]
    for n in sorted(rows, key=lambda x: str(x.get("id") or "")):
        rk = n["refuted_kernel"]
        reading = str(rk.get("reading") or "-")
        why = {"paradigm": "the paradigm carries the gain; try another kernel inside it",
               "unattributed": "the gain is unattributed (local change, kernel refuted): re-measure, not progress",
               "shell": "the gain sits in the other changed components"}.get(reading, reading)
        cands = rk.get("candidates") or []
        out.append(f"- {n.get('id')} (verdict {n.get('verdict') or '-'}): kernel {', '.join(rk.get('kernels') or [])} "
                   f"refuted by {rk.get('ablation')}; build on {rk.get('control')}; reading: {why}"
                   + (f"; candidates: {'; '.join(str(c) for c in cands)}" if cands else "")
                   + (f"; observation {rk.get('observation')}" if rk.get("observation") else ""))
    out.append("")
    return out


def _territory_section(store: Any) -> list[str]:
    rows = [r for r in eutil.read_jsonl(eutil.rpath(store.repo, TOMBSTONES_REL), lenient=True)
            if isinstance(r, dict)]
    out = [TERRITORY_HEADING, "",
           "Tombstones bound a round/lane's published territory, not a cell: each criterion is",
           "one work's absorption boundary, legal as a component, illegal as the claimed kernel.", ""]
    if not rows:
        out.append("- none")
        return out
    shown, older = _newest(rows)
    for r in shown:
        context = r.get("context") if isinstance(r.get("context"), dict) else {}
        where = "/".join(str(x) for x in (context.get("round"), context.get("lane")) if x) or "-"
        out.append(f"- {r.get('id')} ({where}): {_clip(r.get('criterion'), 120)}")
    if older:
        out.append(f"- +{older} older tombstones, see the ledger")
    return out


# ---------------------------------------------------------------- helpers ----
def _newest(items: list) -> tuple[list, int]:
    """The newest LIST_CAP entries (ids are monotonic) and how many were cut."""
    if len(items) <= LIST_CAP:
        return list(items), 0
    return list(items[-LIST_CAP:]), len(items) - LIST_CAP


def _clip(text: Any, width: int) -> str:
    s = " ".join(str(text if text is not None else "").split())
    return s if len(s) <= width else s[:width].rstrip() + "..."


def _num(value: Any) -> str:
    return f"{float(value):g}" if isinstance(value, (int, float)) and not isinstance(value, bool) else "-"
